// foodItems.js

const foodItems = {
    items: [
      { name: "Goat Cheese Salad" },
      { name: "Chicken Confit" },
      { name: "Quiche" },
      { name: "Frangipane Tart" },
      { name: "Guacamole" },
      { name: "Sopaipillas" },
      { name: "Enchiladas" },
      { name: "Pico de Gallo" },
      { name: "Brigadeiro" },
      { name: "Tacaca" },
      { name: "Moqueca" },
      { name: "Bobo De Camaro" },
      { name: "Caipirinha" },
      { name: "Spanakopita" },
      { name: "Mousakka" },
      { name: "Baklava" },
      { name: "Dolmadakia" },
      { name: "Kefthetes" },
      { name: "Pizza Napoletana" },
      { name: "Polenta" },
      { name: "Risotto Milanese" },
      { name: "Eggplant Parmesana" },
      { name: "Mixed Nut Milk Panacotta" },
      { name: "Seafood Paella" },
      { name: "Patatas Bravas" },
      { name: "Churros" },
      { name: "Gazpacho" },
      { name: "Bacalao" },
      { name: "Okonomiyaki" },
      { name: "Miso Soup" },
      { name: "Karaage Chicken" },
      { name: "Doriyaki" },
      { name: "Omu Rice" },
      { name: "Congee" },
      { name: "Kung Pao Chicken" },
      { name: "Pumpkin Pie" },
      { name: "Wonton Soup" },
      { name: "Scallion Pancakes" },
      { name: "Red Ant Chutney" },
      { name: "Baigan Ka Bharta" },
      { name: "Ghevar" },
      { name: "Bisi Bele Bath" },
      { name: "Makki Di Roti Sarso Saag" },
      // Add more food items as needed
    ],
  };
  
  export default foodItems;
  